# Generated by Django 2.2 on 2019-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='production.Profile_of_Actor'),
        ),
        migrations.AlterField(
            model_name='new_movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='production.Profile_of_Director'),
        ),
    ]
