# Generated by Django 2.2 on 2019-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190419_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_movie',
            name='actors',
            field=models.ManyToManyField(to='production.Profile_of_Actor'),
        ),
        migrations.AlterField(
            model_name='new_movie',
            name='directors',
            field=models.ManyToManyField(to='production.Profile_of_Director'),
        ),
    ]
