# Generated by Django 2.2 on 2019-04-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190419_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='new_movie',
            name='directors',
        ),
    ]
