# Generated by Django 2.2 on 2019-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('movie', '0005_auto_20190419_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_movie',
            name='actors',
            field=models.ManyToManyField(to='production.Profile_of_Actor'),
        ),
        migrations.AddField(
            model_name='new_movie',
            name='directors',
            field=models.ManyToManyField(to='production.Profile_of_Director'),
        ),
    ]
