# Generated by Django 2.2 on 2019-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190419_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_movie',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
