# Generated by Django 2.2 on 2019-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_profile_of_user'),
        ('movie', '0007_new_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_movie',
            name='rated_by',
            field=models.ManyToManyField(to='production.Profile_of_User'),
        ),
    ]
