# Generated by Django 2.2 on 2019-04-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_new_movie_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_movie',
            name='total_user_rated',
            field=models.BigIntegerField(default=0),
        ),
    ]
