# Generated by Django 2.2 on 2019-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_new_movie_total_user_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_movie',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
