# Generated by Django 2.2 on 2019-04-23 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_profile_of_user'),
        ('movie', '0010_auto_20190420_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('rated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.new_movie')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Profile_of_User')),
            ],
        ),
    ]
