# Generated by Django 2.2 on 2019-04-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_movie',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='new_movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='new_movie',
            name='total_user_rated',
        ),
    ]
