# Generated by Django 2.2 on 2019-05-09 02:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_profile_of_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0013_auto_20190427_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_movie',
            new_name='NewMovie',
        ),
    ]
